#### Ex 1

In [1]:
import numpy as np

In [5]:
my_array = np.array([2,3,6,4,4,5,4,9,6,7,8])

In [6]:
my_array.mean() 

np.float64(5.2727272727272725)

In [9]:
my_array.std() 

np.float64(2.04898684901539)

In [11]:
my_array = my_array + 5

In [12]:
my_array = my_array * 2

In [13]:
my_array

array([14, 16, 22, 18, 18, 20, 18, 28, 22, 24, 26])

#### Ex 2

In [15]:
matrix = np.arange(12).reshape(4, 3)

In [16]:
matrix_transposed = matrix.T

In [23]:
print(f"Original shape: \n{matrix}")
print(f"\nTransposed shape: \n{matrix_transposed}")

Original shape: 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Transposed shape: 
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


#### Ex 3

In [19]:
arr = np.random.randint(100, 201, 20)

In [21]:
even_nums = arr[arr % 2 == 0]
print("Even numbers:", even_nums)

Even numbers: [178 136 104 188 184 184 138 128 154 118 144]


In [24]:
sliced = arr[2:10]
print("Elements 3rd to 10th:", sliced)

Elements 3rd to 10th: [115 151 136 169 104 171 188 184]


#### Ex 4 

In [25]:
a = np.random.randint(1, 10, 5)
b = np.random.randint(1, 10, 5)
print(f"Array A: {a}")
print(f"\nArray B: {b}")

Array A: [3 8 1 4 1]

Array B: [9 6 3 2 5]


In [26]:
print(f"Addition: {a + b}")
print(f"Subtraction: {a - b}")
print(f"Multiplication: {a * b}")

Addition: [12 14  4  6  6]
Subtraction: [-6  2 -2  2 -4]
Multiplication: [27 48  3  8  5]


#### Ex 5

In [29]:
dataset = np.genfromtxt('../Datasets/data.csv', delimiter=';') 

In [30]:
dataset

array([[ 68.,  91.,  61.,  36.,  78.,  57.,  59.,  34.,  88.],
       [  3.,  92.,  46.,  16.,  10., 100.,  19.,  16.,  87.],
       [ 98.,  39.,  60.,  41.,  23.,  11.,  34.,  41.,  77.],
       [  2.,  64.,  89.,  22.,  61.,  61.,  41.,  72.,  19.],
       [ 55.,  61.,  91.,  48.,  84.,  14.,   6.,  37.,  38.],
       [ 25.,   4.,  43.,   3.,  54.,  43.,  86.,  24.,  65.],
       [ 29.,  74.,  73.,  47.,  11.,  44.,  28.,  37.,  52.],
       [ 14.,  65.,  20.,  57.,  98.,   1.,  44.,  62.,  92.],
       [ 92.,  73.,  77.,  48.,  83.,  39.,  11.,  58.,  47.],
       [ 29.,  59.,  55.,  78.,  27.,  37.,  33.,  51.,  52.],
       [ 67.,  46.,  95., 100.,  89.,  79.,  32.,  67.,  87.],
       [ 90.,  91.,  96.,  97.,  79.,  60.,  73.,  92.,  17.],
       [ 90.,  99.,  22.,  35.,  73.,  84.,  55.,  79.,  74.],
       [ 65.,  64.,  59.,  46.,  67.,  57.,  59.,  22.,   8.],
       [ 62.,  38.,  25.,   3.,  25.,  63.,   6.,  85.,  62.],
       [ 71.,  31.,  75.,  32.,  98.,  98.,   0.,  37.,

In [34]:
print(f"Sum: {np.sum(dataset)}")
print(f"Mean: {np.mean(dataset)}")
print(f"Median: {np.median(dataset)}")

Sum: 7679.0
Mean: 53.326388888888886
Median: 57.0


In [37]:
col_data = dataset[:, 0]  # the first column
print(f"\nColumn sum: {np.sum(col_data)}")
print(f"Column mean: {np.mean(col_data)}")
print(f"Column median: {np.median(col_data)}")


Column sum: 860.0
Column mean: 53.75
Column median: 63.5
